# Generated by Django 5.2.6 on 2025-10-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collaboration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="photos/"
            ),
        ),
    ]
