# Generated by Django 5.2.6 on 2025-09-25 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollabUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaborator_phone', models.CharField(blank=True, max_length=20)),
                ('collaborator_department', models.CharField(blank=True, max_length=20)),
                ('collaborator_university', models.CharField(blank=True, max_length=20)),
                ('collaborator_date_of_birth', models.DateField(blank=True)),
                ('collaborator_university_id', models.CharField(blank=True, max_length=20)),
                ('collaborator_type', models.CharField(blank=True, max_length=20)),
                ('collaborator_joined_on', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
