# Generated by Django 5.2.6 on 2025-09-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collabuser',
            name='collaborator_about',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='collabuser',
            name='collaborator_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collabuser',
            name='collaborator_department',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='collabuser',
            name='collaborator_phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='collabuser',
            name='collaborator_type',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='collabuser',
            name='collaborator_university',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='collabuser',
            name='collaborator_university_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
