# Generated by Django 5.2.6 on 2025-09-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_collabuser_collaborator_about_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collabuser",
            name="collaborator_about",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="collabuser",
            name="collaborator_department",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="collabuser",
            name="collaborator_phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="collabuser",
            name="collaborator_type",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="collabuser",
            name="collaborator_university",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="collabuser",
            name="collaborator_university_id",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
